/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shane' at '9/19/16 7:50 PM' with Gradle 2.9
 *
 * @author shane, @date 9/19/16 7:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
